app/bp/__init__.py
from flask import Blueprint

bp = Blueprint('bp',__name__)

from . import routes

app/bp/routes.py
from flask import render_template, request
from . import bp
from ..models import User, Category, Tag, Post, db, Track

@bp.route('/')
def index():
	catid=request.args.get('catid')
	tracker = Track(
		ip = request.remote_addr,
		category = catid
	)
	db.session.add(tracker)
	db.session.commit()
	return render_template('bp/index.html', User=User, Category=Category, Tag = Tag, catid = catid)

@bp.route('/post/<slug>')
def viewPost(slug):
    post = Post.query.filter_by(url=slug).first()
    return render_template('bp/post.html', post=post, User=User, Category=Category, Tag = Tag)

@bp.app_errorhandler(404)
def err404(e):
	return render_template('404.html'),404

app/templates/bp/index.html
{% extends "base.html" %}
{% block page_content %}

<div class="row">
    <div id="main">
        <div class="col-md-9 col-md-push-0">
            <div class="post">
            <div class="category_banner">
                <!--{% if catid %}-->
                <!--<h2>Category: {{Category.query.filter_by(id=catid).first().name}}</h2>-->
                <!--{%endif%}-->
            </div>
            {% for post in getPosts(catid) %}
                <div class="post-loop">
            <p class="date pull-right">
                {{moment(post.timestamp).format('LL')}}
            </p>
            <a href="{{url_for('.viewPost',slug=post.url)}}"><h1 class="post-title">{{post.title}}</h1></a>
            <div class="posted">Posted by
                <span class="label label-primary" >{{User.query.filter_by(id=post.user_id).first().firstname | capitalize}}</span>
            in category <span class="label label-danger"><a class="span-url" href="{{ url_for('bp.index', catid=post.category_id) }}">{{Category.query.filter_by(id=post.category_id).first().name}}</a></span>
               <hr class="post-line">


            </div>
            <div class="post-body">
                <p>{{post.intro_text | safe}}</p>
            </div>
            <div class="post-trailer">

                <span class="pull-left"><a href="{{url_for('.viewPost',slug=post.url)}}">Read more ...</a> </span>
                <span class="pull-right"><a href="#">Comments</a> </span>
                <br>
                    <p>
                    <br>
                <span class="pull-left tags">Tags -&nbsp;
                    {% for tags in post.tag_id.split(',') %}
                    <span class="pull-right"><span class="label label-default">{{tags | title}}</span>&nbsp;</span>
                    {% endfor %}
                    </span>


                </p>
                </div>
            <br>
                </div>
            {%endfor%}
                </div>
            <br>
        </div>
    </div>
</div>
{% endblock %}

app/templates/bp/post.html
{% extends "base.html" %}
{% block page_content %}

<div class="row">
    <div id="main">
        <div class="col-md-9 col-md-push-0">
            <div class="post">
                <div class="post-loop">
            <p class="date pull-right">
                {{moment(post.timestamp).format('LL')}}
            </p>
            <h1 class="post-title">{{post.title}}</h1>
            <div class="posted">Posted by
                <span class="label label-primary" >{{User.query.filter_by(id=post.user_id).first().firstname | capitalize}}</span>
            in category <span class="label label-danger">{{Category.query.filter_by(id=post.category_id).first().name}}</span>
                   <p>
                    <br>
                <span class="pull-left tags">Tags -&nbsp;
                    {% for tags in post.tag_id.split(',') %}
                    <span class="pull-right"><span class="label label-default">{{tags | title}}</span>&nbsp;</span>
                    {% endfor %}
                    </span>
                <br>
                    <hr class="post-line">
                </p>
            </div>
            <div class="post-body">
                <p>{{post.body | safe}}</p>
            </div>
            <!--<div class="post-trailer">-->
                <!--<span class="pull-left"><a href="#">Read more ...</a> </span>-->
                <!--<span class="pull-right"><a href="#">Comments</a> </span>-->
                <!--</div>-->
                </div>
                </div>
            <br>
        </div>
    </div>
</div>
{% endblock %}